version: '3.9'

services:
  rabbitmq:
      image: rabbitmq:3-management
      hostname: rabbitmq
      ports:
       - "5672:5672"
       - "15672:15672"
      environment:
       RABBITMQ_DEFAULT_USER: guest
       RABBITMQ_DEFAULT_PASS: guest
      networks:
       - backend
      healthcheck:
       test: ["CMD", "rabbitmqctl", "status"]
       interval: 10s
       timeout: 5s
       retries: 5



  database:
      build: ./database
      depends_on:
       redis:         
         condition: service_healthy
      environment:
       - REDIS_URL=redis://redis:6379
      volumes:
       - ./data:/app/data
      networks:
       - backend
      healthcheck:
       test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('rabbitmq',5672)); s.close()"]
       interval: 10s
       timeout: 5s
       retries: 5

  uploader:
      build: ./uploader_service
      ports:
       - "8010:8010"
      depends_on:
       database:
        condition: service_healthy       
       worker:       
        condition: service_healthy       
       redis:
        condition: service_healthy       
       rabbitmq:
        condition: service_healthy
      environment:
       - REDIS_URL=redis://redis:6379
      networks:
       - backend
      healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 20s
       
  worker:
      build: ./yolo_worker
      environment:
       - REDIS_URL=redis://redis:6379
      volumes:
       - ./data:/app/data
      depends_on:
       redis:
        condition: service_healthy
       rabbitmq:
        condition: service_healthy
      networks:
       - backend
      healthcheck:
       test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('rabbitmq',5672)); s.close()"]
       interval: 10s
       timeout: 5s
       retries: 5

  redis:
      image: redis:7-alpine
      container_name: redis_service
      ports:
       - "6379:6379"
      networks:
       - backend
      healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 10s
       timeout: 5s
       retries: 5

networks:
  backend:
    driver: bridge

